export enum DEPARTMENTS {
  MICROBIOLOGY = 1,
  FOOD_SCIENCE = 2,
  BIOCHEMISTRY = 3,
  GEOLOGY = 4,
  BIOLOGICAL_SCIENCES = 5,
  PHYSICS = 6,
  COMPUTER_SCI_MATH = 7,
  CHEMICAL_SCIENCES = 8,
  PHYSICAL_SCIENCE = 9,
  GEOPHYSICS = 10,
  ACCOUNTING = 11,
  MASS_COMMUNICATION = 12,
  BUSINESS_ADMIN = 13,
  MUSIC = 14,
  LANGUAGES = 15,
  ECONOMICS = 16,
  PHILOSOPHY_RELIGION = 17,
  IRPM = 18,
}


export enum GENRES{
  
}